### ISSUE TITLE
Tree-like construction 

### ISSUE THREAD

**Issue by ghost** [NLPbox/codra-service#2]
Thanks for this repo. Do you know how to create a tree from the output as in this demo?
For ex: if we execute:  "Although they didn't like him, they accepted the offer."
[http://alt.qcri.org/demos/Discourse_Parser_Demo/](url)
Thanks

**Comment by arne-cl** [comment]
Dear @moh55m55,
did you find a solution? I don't know how the CODRA demo does it. I didn't find anything related in the codebase.

If you need a browser-based visualization, you might try this one: https://bvjebin.github.io/JSONTree/

**Comment by ghost** [comment]
I do not. I am not interested anymore. I tried "treelib" and it seems good to construct a basic tree but not like the one in the demo.

**Comment by arne-cl** [comment]
I just realized that the demo uses d3.js and the code to render the tree is actually run client-side in the browser and embedded in the HTML.
